#!/usr/bin/env bash
#  A Script that configures a new Ubuntu machine to Perform a 301-redirection

# Upadating Packages before Installations
sudo apt-get update
sudo apt-get install -y nginx

# Creating an index.html page
echo "Hello World!" | sudo tee /var/www/html/index.html

# Performing a 301 Redirection
string_for_replacement="\\\n\tlocation = /redirect_me {\n\t\t return 301 https:\/\/github.com\/Emtuchi;\n\t}\n"

sudo sed -i "53i $string_for_replacement" /etc/nginx/sites-enabled/default

# Restarting Nginx service
sudo service nginx restart
