#!/usr/bin/env bash
# Customizing a 404-error_page

# Updating Packages before performing installations
sudo apt-get update
sudo apt-get install -y nginx

# Creating an index.html page
echo "Hello World!" | sudo tee /var/www/html/index.html

# Performing a "moved permanently redirection" (301)
new_string="\\\n\tlocation /redirect_me {\n\t\t return 301 https:\/\/github.com\/Emtuchi;\n\t}\n"
sudo sed -i "53i $new_string" /etc/nginx/sites-enabled/default

# Creating a 404 Custom error page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html > /dev/null

error="\\\n\terror_page 404 /404.html;\n\n\tlocation = /404.html {\n\t\tinternal;\n\t}"

sudo sed -i "53i $error" /etc/nginx/sites-enabled/default

header="\\\nadd_header X-Served-By \$hostname;"
sudo sed =i "53i $header" /etc/nginx/sites-enabled/default

# Testing configurations for syntax errors
sudo nginx -t

# restart nginx after implementing changes
sudo service nginx restart
